### Get all service requests
GET http://localhost:8080/api/service-requests

### Create service request
POST http://localhost:8080/api/service-requests
Content-Type: application/json

{
  "title": "",
  "description": "",
  "priority": "",
  "status": ""
}

### Create service request
POST http://localhost:8080/api/service-requests
Content-Type: application/json

{
  "title": "Database connection issue",
  "description": "Unable to connect to production database",
  "priority": "HIGH",
  "status": "OPEN"
}

### Create another request
POST http://localhost:8080/api/service-requests
Content-Type: application/json

{
  "title": "API performance issue",
  "description": "API response time is above the expected threshold",
  "priority": "CRITICAL",
  "status": "IN_PROGRESS"
}

### Invalid priority
POST http://localhost:8080/api/service-requests
Content-Type: application/json

{
  "title": "Invalid priority test",
  "description": "Testing enum validation",
  "priority": "SUPER_HIGH",
  "status": "OPEN"
}

### Invalid status
POST http://localhost:8080/api/service-requests
Content-Type: application/json

{
  "title": "Invalid status test",
  "description": "Testing enum validation",
  "priority": "HIGH",
  "status": "PENDING"
}

### Missing priority
POST http://localhost:8080/api/service-requests
Content-Type: application/json

{
  "title": "Missing priority test",
  "description": "Testing validation",
  "status": "OPEN"
}

### Missing priority - Test malformed json
POST http://localhost:8080/api/service-requests
Content-Type: application/json

{
  "title": "Broken JSON"
  "description": "Missing comma"
}

### Malformed JSON
POST http://localhost:8080/api/service-requests
Content-Type: application/json

{
  "title": "Database issue",
  "description": "Testing malformed JSON",
  "priority": "HIGH",
  "status": "OPEN"

### Get service request
GET http://localhost:8080/api/service-requests/1

### Get service request - Test non existence id
GET http://localhost:8080/api/service-requests/999999

### Update Service Request
PUT http://localhost:8080/api/service-requests/1
Content-Type: application/json

{
  "title": "Database connection issue - resolved",
  "description": "Database connectivity has been restored",
  "priority": "MEDIUM",
  "status": "CLOSED"
}

### Delete Service Request
DELETE http://localhost:8080/api/service-requests/1