package com.sailaja.aiserviceplatform.service;

import com.sailaja.aiserviceplatform.repository.ServiceRequestRepository;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import com.sailaja.aiserviceplatform.dto.ServiceRequestRequest;
import com.sailaja.aiserviceplatform.dto.ServiceRequestResponse;
import com.sailaja.aiserviceplatform.entity.ServiceRequest;
import com.sailaja.aiserviceplatform.enums.Priority;
import com.sailaja.aiserviceplatform.enums.ServiceRequestStatus;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;
import java.util.Optional;
import org.mockito.ArgumentCaptor;
import com.sailaja.aiserviceplatform.exception.ResourceNotFoundException;
import static org.junit.jupiter.api.Assertions.assertThrows;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import java.util.List;

@ExtendWith(MockitoExtension.class)
class ServiceRequestServiceTest {

    @Mock
    private ServiceRequestRepository repository;

    private ServiceRequestService service;

    @Test
    void testCreateRequest() {

        service = new ServiceRequestService(repository);
        ServiceRequestRequest request = new ServiceRequestRequest(
                "Database connection issue",
                "Unable to connect to production database",
                Priority.HIGH,
                ServiceRequestStatus.OPEN
        );

        when(repository.save(any(ServiceRequest.class)))
                .thenAnswer(invocation -> {
                    ServiceRequest entity = invocation.getArgument(0);

                    // Simulate the ID generated by the database.
                    // Our entity intentionally does not expose setId().
                    return entity;
                });

        ServiceRequestResponse response = service.createRequest(request);

        assertEquals("Database connection issue", response.title());
        assertEquals(Priority.HIGH, response.priority());
        assertEquals(ServiceRequestStatus.OPEN, response.status());

        ArgumentCaptor<ServiceRequest> serviceRequestCaptor =
                ArgumentCaptor.forClass(ServiceRequest.class);

        verify(repository).save(serviceRequestCaptor.capture());

        ServiceRequest capturedEntity = serviceRequestCaptor.getValue();

        assertEquals("Database connection issue", capturedEntity.getTitle());
        assertEquals(
                "Unable to connect to production database",
                capturedEntity.getDescription()
        );
        assertEquals(Priority.HIGH, capturedEntity.getPriority());
        assertEquals(ServiceRequestStatus.OPEN, capturedEntity.getStatus());

    }

    @Test
    void testGetRequestById() {

        service = new ServiceRequestService(repository);

        ServiceRequest entity = new ServiceRequest();
        entity.setTitle("Database connection issue");
        entity.setDescription("Unable to connect to production database");
        entity.setPriority(Priority.HIGH);
        entity.setStatus(ServiceRequestStatus.OPEN);

        when(repository.findById(1L))
                .thenReturn(Optional.of(entity));

        ServiceRequestResponse response = service.getRequestById(1L);

        assertEquals("Database connection issue", response.title());
        assertEquals(
                "Unable to connect to production database",
                response.description()
        );
        assertEquals(Priority.HIGH, response.priority());
        assertEquals(ServiceRequestStatus.OPEN, response.status());

        verify(repository).findById(1L);
    }

    @Test
    void testGetRequestById_notFound() {

        service = new ServiceRequestService(repository);

        when(repository.findById(999L))
                .thenReturn(Optional.empty());

        ResourceNotFoundException exception = assertThrows(
                ResourceNotFoundException.class,
                () -> service.getRequestById(999L)
        );

        assertEquals(
                "Service request not found with id: 999",
                exception.getMessage()
        );

        verify(repository).findById(999L);
    }

    @Test
    void testGetAllRequests() {

        service = new ServiceRequestService(repository);

        ServiceRequest firstRequest = new ServiceRequest();
        firstRequest.setTitle("Database connection issue");
        firstRequest.setDescription("Unable to connect to production database");
        firstRequest.setPriority(Priority.HIGH);
        firstRequest.setStatus(ServiceRequestStatus.OPEN);

        ServiceRequest secondRequest = new ServiceRequest();
        secondRequest.setTitle("API timeout issue");
        secondRequest.setDescription("External API is timing out");
        secondRequest.setPriority(Priority.CRITICAL);
        secondRequest.setStatus(ServiceRequestStatus.IN_PROGRESS);

        when(repository.findAll())
                .thenReturn(List.of(firstRequest, secondRequest));

        List<ServiceRequestResponse> responses =
                service.getAllRequests();

        assertEquals(2, responses.size());

        assertEquals("Database connection issue", responses.get(0).title());
        assertEquals(Priority.HIGH, responses.get(0).priority());
        assertEquals(ServiceRequestStatus.OPEN, responses.get(0).status());

        assertEquals("API timeout issue", responses.get(1).title());
        assertEquals(Priority.CRITICAL, responses.get(1).priority());
        assertEquals(ServiceRequestStatus.IN_PROGRESS, responses.get(1).status());

        verify(repository).findAll();
    }

    @Test
    void testUpdateRequest() {

        service = new ServiceRequestService(repository);

        ServiceRequest existingRequest = new ServiceRequest();
        existingRequest.setTitle("Old title");
        existingRequest.setDescription("Old description");
        existingRequest.setPriority(Priority.LOW);
        existingRequest.setStatus(ServiceRequestStatus.OPEN);

        ServiceRequestRequest updateRequest = new ServiceRequestRequest(
                "Updated title",
                "Updated description",
                Priority.CRITICAL,
                ServiceRequestStatus.IN_PROGRESS
        );

        when(repository.findById(1L))
                .thenReturn(Optional.of(existingRequest));

        when(repository.save(any(ServiceRequest.class)))
                .thenAnswer(invocation -> invocation.getArgument(0));

        ServiceRequestResponse response =
                service.updateRequest(1L, updateRequest);

        assertEquals("Updated title", response.title());
        assertEquals("Updated description", response.description());
        assertEquals(Priority.CRITICAL, response.priority());
        assertEquals(ServiceRequestStatus.IN_PROGRESS, response.status());

        verify(repository).findById(1L);
        verify(repository).save(existingRequest);
    }

    @Test
    void testUpdateRequest_notFound() {

        service = new ServiceRequestService(repository);

        ServiceRequestRequest updateRequest = new ServiceRequestRequest(
                "Updated title",
                "Updated description",
                Priority.HIGH,
                ServiceRequestStatus.IN_PROGRESS
        );

        when(repository.findById(999L))
                .thenReturn(Optional.empty());

        ResourceNotFoundException exception = assertThrows(
                ResourceNotFoundException.class,
                () -> service.updateRequest(999L, updateRequest)
        );

        assertEquals(
                "Service request not found with id: 999",
                exception.getMessage()
        );

        verify(repository).findById(999L);
    }

    @Test
    void testDeleteRequest() {

        service = new ServiceRequestService(repository);

        ServiceRequest existingRequest = new ServiceRequest();
        existingRequest.setTitle("Database connection issue");
        existingRequest.setDescription("Unable to connect to production database");
        existingRequest.setPriority(Priority.HIGH);
        existingRequest.setStatus(ServiceRequestStatus.OPEN);

        when(repository.findById(1L))
                .thenReturn(Optional.of(existingRequest));

        service.deleteRequest(1L);

        verify(repository).findById(1L);
        verify(repository).delete(existingRequest);
    }

    @Test
    void testDeleteRequest_notFound() {

        service = new ServiceRequestService(repository);

        when(repository.findById(999L))
                .thenReturn(Optional.empty());

        ResourceNotFoundException exception = assertThrows(
                ResourceNotFoundException.class,
                () -> service.deleteRequest(999L)
        );

        assertEquals(
                "Service request not found with id: 999",
                exception.getMessage()
        );

        verify(repository).findById(999L);
    }
}